tasks:
  - name: appdev-week3-graphql
    init: |
      cd /workspace/appdev-week3-graphql
      nvm install node
      npm install -g npm@latest
    command: |
      cd /workspace/appdev-week3-graphql
      echo "appdev-week3-graphql gitpod ready - LET'S DO THIS!"
      npm install
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore      
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
